### ISSUE TITLE
RuntimeError: set_storage is not allowed on Tensor created from .data or .detach()

### ISSUE THREAD

**Issue by lwgkzl** [guoday/CCF-BDCI-Sentiment-Analysis-Baseline#1]
![image](https://user-images.githubusercontent.com/30727306/64784609-11662780-d59d-11e9-9567-aa0b00e936ea.png)
跑roberta的时候出现了这个问题，麻烦郭大帮忙看下

**Comment by lwgkzl** [comment]
谢谢郭大~

**Comment by guoday** [comment]
> 谢谢郭大~

已修复
