### ISSUE TITLE
bert输出层对截断部分怎么融合

### ISSUE THREAD

**Issue by zerohd4869** [guoday/CCF-BDCI-Sentiment-Analysis-Baseline#10]
请问bert输出层截断部分融合怎么处理的，代码体现在哪里，谢谢回复！

**Comment by guoday** [comment]
> 请问bert输出层截断部分融合怎么处理的，代码体现在哪里，谢谢回复！

https://github.com/guoday/CCF-BDCI-Sentiment-Analysis-Baseline/blob/master/pytorch_transformers/modeling_bert.py:line 995-1005

**Comment by zerohd4869** [comment]
Thanks♪(･ω･)ﾉ
