### ISSUE TITLE
我看分类的demo上，是在bert之后接了一个lstm层吗，

### ISSUE THREAD

**Issue by lx-rookie** [guoday/CCF-BDCI-Sentiment-Analysis-Baseline#11]
是的话lstm的输入是bert的输出的第一向量，还是所有的输出呢

**Comment by lx-rookie** [comment]
因为没用过pytorch，所以在源码上没太看出来怎么做的，克一告知下吗

**Comment by lx-rookie** [comment]
还有我有试过在后面接cnn层，用的是bert的所有输出，但是效果比不上直接使用第一向量接分类层的效果好，这是为什么呢

**Comment by guoday** [comment]
> 还有我有试过在后面接cnn层，用的是bert的所有输出，但是效果比不上直接使用第一向量接分类层的效果好，这是为什么呢
1.源代码的位置可以直接看已经close的issues
2.lstm的输入是输出的第一向量
3.句内的交互已经在bert完成了，没必要用所有输出，所以只需用第一向量来完成句子间的交互

**Comment by lx-rookie** [comment]
好的，那有没有试过再后面接一维卷积层呢，只用第一向量的话不就没法接cnn层了，加一个lstm层普遍有比直接分类层效果好吗

**Comment by guoday** [comment]
> 好的，那有没有试过再后面接一维卷积层呢，只用第一向量的话不就没法接cnn层了，加一个lstm层普遍有比直接分类层效果好吗

一段话分成K句，每句取第一个向量，就有k个向量，依旧能用cnn层。直接效果，自己尝试下吧

**Comment by lx-rookie** [comment]
好的，感谢答疑
