### ISSUE TITLE
咨询一个问题：这些模型无显卡的笔记本能跑嘛？

### ISSUE THREAD

**Issue by Klauszhao** [guoday/CCF-BDCI-Sentiment-Analysis-Baseline#12]
其实知道跑是可以跑的，只是花费的时间问题，因为实在没有这么多计算资源，很多模型都不尝试，直接放弃，kaggle上有 gpu资源，想回头去尝试一下，因此还是想咨询你一下，你这个模型跑完多久？

**Comment by guoday** [comment]
> 其实知道跑是可以跑的，只是花费的时间问题，因为实在没有这么多计算资源，很多模型都不尝试，直接放弃，kaggle上有 gpu资源，想回头去尝试一下，因此还是想咨询你一下，你这个模型跑完多久？

没有GPU需要3-4天，Kaggle的gpu  估计需要1天左右
