### ISSUE TITLE
/home/ming/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.   'recall', 'true', average, warn_for) test 0.06457949662369551

### ISSUE THREAD

**Issue by wvdon** [guoday/CCF-BDCI-Sentiment-Analysis-Baseline#14]
/home/ming/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
test 0.06457949662369551
F1正常，test值低，而且出现这样的报错，寻求许久，未解决，请问这是因为什么？

**Comment by guoday** [comment]
因为test集的标签是假的，全为0。只有交到排行榜才有成绩

**Comment by guoday** [comment]
> /home/ming/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
> 'recall', 'true', average, warn_for)
> test 0.06457949662369551
> F1正常，test值低，而且出现这样的报错，寻求许久，未解决，请问这是因为什么？

因为test集的标签是假的，全为0。只有交到排行榜才有成绩

**Comment by wvdon** [comment]
> > /home/ming/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
> > 'recall', 'true', average, warn_for)
> > test 0.06457949662369551
> > F1正常，test值低，而且出现这样的报错，寻求许久，未解决，请问这是因为什么？
> 
> 因为test集的标签是假的，全为0。只有交到排行榜才有成绩



> > /home/ming/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
> > 'recall', 'true', average, warn_for)
> > test 0.06457949662369551
> > F1正常，test值低，而且出现这样的报错，寻求许久，未解决，请问这是因为什么？
> 
> 因为test集的标签是假的，全为0。只有交到排行榜才有成绩

当我尝试迁移数据训练时，导出的sub.csv里面没有标签为2的值，这个让我很奇怪。
输入数据也为三分类，标签是0,1,2，f1正常。
pp['label'].value_counts()
0    7901
1    2099
Name: label, dtype: int64

**Comment by guoday** [comment]
> > > /home/ming/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
> > > 'recall', 'true', average, warn_for)
> > > test 0.06457949662369551
> > > F1正常，test值低，而且出现这样的报错，寻求许久，未解决，请问这是因为什么？
> > 
> > 
> > 因为test集的标签是假的，全为0。只有交到排行榜才有成绩
> 
> > > /home/ming/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
> > > 'recall', 'true', average, warn_for)
> > > test 0.06457949662369551
> > > F1正常，test值低，而且出现这样的报错，寻求许久，未解决，请问这是因为什么？
> > 
> > 
> > 因为test集的标签是假的，全为0。只有交到排行榜才有成绩
> 
> 当我尝试迁移数据训练时，导出的sub.csv里面没有标签为2的值，这个让我很奇怪。
> 输入数据也为三分类，标签是0,1,2，f1正常。
> pp['label'].value_counts()
> 0 7901
> 1 2099
> Name: label, dtype: int64

不是很了解你的问题是什么。test值不就是F1,为什么又说test值低但F1正常？sub.csv的输出应该是label_0,label_1,label_2的概率。怎么会没有标签为2的值呢？

**Comment by guoday** [comment]
> > > /home/ming/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
> > > 'recall', 'true', average, warn_for)
> > > test 0.06457949662369551
> > > F1正常，test值低，而且出现这样的报错，寻求许久，未解决，请问这是因为什么？
> > 
> > 
> > 因为test集的标签是假的，全为0。只有交到排行榜才有成绩
> 
> > > /home/ming/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
> > > 'recall', 'true', average, warn_for)
> > > test 0.06457949662369551
> > > F1正常，test值低，而且出现这样的报错，寻求许久，未解决，请问这是因为什么？
> > 
> > 
> > 因为test集的标签是假的，全为0。只有交到排行榜才有成绩
> 
> 当我尝试迁移数据训练时，导出的sub.csv里面没有标签为2的值，这个让我很奇怪。
> 输入数据也为三分类，标签是0,1,2，f1正常。
> pp['label'].value_counts()
> 0 7901
> 1 2099
> Name: label, dtype: int64

如果你用的是这个比赛的数据，test的值就是这样，因为已经说了，test数据集label是不可见的。只有交到排行榜才能知道真实的F1

**Comment by wvdon** [comment]
> > > > /home/ming/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
> > > > 'recall', 'true', average, warn_for)
> > > > test 0.06457949662369551
> > > > F1正常，test值低，而且出现这样的报错，寻求许久，未解决，请问这是因为什么？
> > > 
> > > 
> > > 因为test集的标签是假的，全为0。只有交到排行榜才有成绩
> > 
> > 
> > > > /home/ming/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
> > > > 'recall', 'true', average, warn_for)
> > > > test 0.06457949662369551
> > > > F1正常，test值低，而且出现这样的报错，寻求许久，未解决，请问这是因为什么？
> > > 
> > > 
> > > 因为test集的标签是假的，全为0。只有交到排行榜才有成绩
> > 
> > 
> > 当我尝试迁移数据训练时，导出的sub.csv里面没有标签为2的值，这个让我很奇怪。
> > 输入数据也为三分类，标签是0,1,2，f1正常。
> > pp['label'].value_counts()
> > 0 7901
> > 1 2099
> > Name: label, dtype: int64
> 
> 如果你用的是这个比赛的数据，test的值就是这样，因为test数据集label是不可见的，我在数据处理的时候，把全部label置为0了。只有交到排行榜才能知道真实的F1

非常感谢你！
