### ISSUE TITLE
您好，既然test集的全是假标签0为什么还要导进去dataloader里面？

### ISSUE THREAD

**Issue by chenjinhua1993** [guoday/CCF-BDCI-Sentiment-Analysis-Baseline#16]
![image](https://user-images.githubusercontent.com/35960345/76515077-f153ea00-6493-11ea-99f4-b763f35c7e9d.png)
在昨天在运行过程中遇到一个坑，就是pytorch的标签不能为负数，不知道是不是这个原因，所以要显式的规定test集的标签？能否直接用没有标签的数据直接预测。（另外，昨天发现，如果下载的是pytorch版本的权重，就不需要进行转换了，直接bash run_roberta.sh 即可。）

**Comment by guoday** [comment]
> ![image](https://user-images.githubusercontent.com/35960345/76515077-f153ea00-6493-11ea-99f4-b763f35c7e9d.png)
> 在昨天在运行过程中遇到一个坑，就是pytorch的标签不能为负数，不知道是不是这个原因，所以要显式的规定test集的标签？能否直接用没有标签的数据直接预测。（另外，昨天发现，如果下载的是pytorch版本的权重，就不需要进行转换了，直接bash run_roberta.sh 即可。）

1.标签不能负数。但是我在test并没有把label输入到模型中，见line 573。如果你不想用标签直接预测，只需把label相关的变量全部删掉即可。
2.直接下载pytorch的权重不需要转化

**Comment by chenjinhua1993** [comment]
好的，感谢回答！

**Comment by chenjinhua1993** [comment]
![image](https://user-images.githubusercontent.com/35960345/76521532-f6b73180-649f-11ea-9147-d76e628775a7.png)
您好，还有个问题，如果某个GPU的内存利用率比起其他三个高，是否属于正常情况？

**Comment by guoday** [comment]
> ![image](https://user-images.githubusercontent.com/35960345/76521532-f6b73180-649f-11ea-9147-d76e628775a7.png)
> 您好，还有个问题，如果某个GPU的内存利用率比起其他三个高，是否属于正常情况？

一般来说，第一个GPU都会比其他的高，并且其他的应该是相同的利用率，这是正常的。因为第一张卡需要存在保存模型的参数和数据

**Comment by chenjinhua1993** [comment]
好的，明白，非常感谢！
