### ISSUE TITLE
Roberta-large 与Roberta-mid的差别

### ISSUE THREAD

**Issue by DeligientSloth** [guoday/CCF-BDCI-Sentiment-Analysis-Baseline#5]
Roberta-large 与Roberta-mid的差别R只是参数max_seq_length=512, split_num=1，直接修改一下脚本就可以？

**Comment by guoday** [comment]
https://github.com/brightmart/roberta_zh 从该网站下载large模型权重

**Comment by DeligientSloth** [comment]
> https://github.com/brightmart/roberta_zh 从该网站下载large模型权重

除了权重之外，参数还修改为max_seq_length=512, split_num=1吗？

**Comment by guoday** [comment]
> https://github.com/brightmart/roberta_zh 从该网站下载large模型权重
> 
> 除了权重之外，参数还修改为max_seq_length=512, split_num=1吗？

是的
