### ISSUE TITLE
为什么robert.sh 用的是run_bert.py呢

### ISSUE THREAD

**Issue by ZLKong** [guoday/CCF-BDCI-Sentiment-Analysis-Baseline#7]
你好，

请问为什么robert.sh 用的是run_bert.py呢
是因为roberta的模型可以在bert上finetune吗？
另外我尝试用albert的预训练模型在run_bert.py上跑，结果显示torch
size 不匹配， 一个是[21128, 2048]，一个是(21128, 128)

**Comment by guoday** [comment]
> 你好，
> 请问为什么robert.sh 用的是run_bert.py呢
> 是因为roberta的模型可以在bert上finetune吗？
> 另外我尝试用albert的预训练模型在run_bert.py上跑，结果显示torch
> size 不匹配， 一个是[21128, 2048]，一个是(21128, 128)

1.roberta和bert是同一模型，不同的初始化参数，所以都是用run_bert.py
2.albert和bert是不同的模型，所以没法用run_bert.py

**Comment by ZLKong** [comment]
好的，我明白了，谢谢
